version: '3.8'
services:
    contacts:
        ports:
            - '80:80'
        container_name: contacts
        #network_mode: contactsnetwork  # it's own when started
        image: contacts
        build: 
          dockerfile: ./Dockerfile
        restart: on-failure 
    mssql:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStrongPassword12#
        ports:
            - 1433:1433
        #network_mode: contactsnetwork # it's own when started
        volumes:
            - sqldata:/var/opt/mssql
        container_name: sqlserver # as in the connection string
        image: mcr.microsoft.com/mssql/server:latest
        deploy:
volumes:
  sqldata: 
    external: true